### ISSUE TITLE
Can't scroll in landscape mode

### ISSUE THREAD

**Issue by Hopelezz** [paabloLC/astro-neumorphismt#16]
![Screenshot_20220826-105813_Chrome.jpg](https://user-images.githubusercontent.com/72772558/186945603-1332877a-df66-424c-9242-a5a3c4148920.jpg)

**Comment by paabloLC** [comment]
Thank you for the rapid review; much appreciated.

I also have in mind to redone some mobile views due to old devices do not look as expected, so, I will fix also this issue for landscape.

PS: Of course, people could feel free to create issues or submit PRs.

Thank you @Hopelezz ! have a good weekend =)

**Comment by paabloLC** [comment]
@Hopelezz I did a big refactor to fix this problem. 

Now, the scroll is available for all resolutions till the desktop view. I think this improvement should make the UX feel better.

Check it if you want and let me know what you think about it, thank you Sr !! =))

P.S: I still did nothing related to the other issue that you created. (text overlapping or so), this PR is only for scrolling and improvement in the main box.

**Comment by paabloLC** [comment]
This is done, the issue can be closed =)
